version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_AUTH_CREDENTIALS_FILE=
      - CHROMA_SERVER_AUTH_CREDENTIALS=
      - CHROMA_SERVER_AUTH_PROVIDER=
    restart: unless-stopped
